# config file for VPAL: (1-p(x))*mu_s(x) + p(x)*mu_d(x,t)

select_model = VPAL

model{
    probgrid{
      otype = HashGrid
      n_levels = 12
      n_features_per_level = 8
      log2_hashmap_size = 19
      base_resolution = 8
      per_level_scale = 1.45
    }
    hash3dgrid{
      otype = HashGrid
      n_levels = 12
      n_features_per_level = 8
      log2_hashmap_size = 19
      base_resolution = 8
      per_level_scale = 1.45
    }
    hash4dgrid{
      otype = HashGrid
      n_levels = 12
      n_features_per_level = 8
      log2_hashmap_size = 19
      base_resolution = 2
      per_level_scale = 1.4
    }
    coarse2fine{
      enabled = True
      init_active_level_prob = 4
      init_active_level_3d = 4
      init_active_level_4d = 4
      step_prob = 2500
      step_3d = 2500
      step_4d = 2500
    }
    probnet{
      otype = FullyFusedMLP
      activation = ReLU
      output_activation = Sigmoid
      n_neurons = 128
      n_hidden_layers = 3      
    }
    net3d{
      otype = FullyFusedMLP
      activation = ReLU
      output_activation = ReLU
      n_neurons = 128
      n_hidden_layers = 3      
    }
    net4d{
      otype = FullyFusedMLP
      activation = ReLU 
      output_activation = ReLU
      n_neurons = 128
      n_hidden_layers = 3        
    }
}

render {
    ray_seen = 2048   # render ray batch size for seen views
    factor = 2  # uniform sample interval
    sample_mode = equaldist # equal sample distance
    chunksize = 65536 # maximum ray chunk size
}

# lr = 7.5e-4
optim_nerf {
    type = Adam
    params = {
      lr_p = 7.5e-4
      lr_s = 7.5e-4
      lr_d = 7.5e-4
      weight_decay = 0.0
    }
    sched = {
      type = step  # step/CA/CAWR
      step_param = {
        step_size = 5000
        gamma = 0.9
      }
    }
}

print{
    print_interval = 1
    save_interval = 1000000
    vis_interval = 100000
}

flow_consistency {
    enabled = True
    perturb_rays = 1024
    TP_std = 1
    beta = 10
}

loss{
    prob_reg_weight = 0.01
    prob_entropy_weight = 0
}

fusion{
    mode = simple_avg  # only support avg fusion
}

occgrid{
    enabled = False
    s_rate = 4
    thres = 0.01
    updata_n = 16
}